name: Deploy
on: [pull_request]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #  your build commands
      # - run: |
      #    ng build --prod
      - uses: amondnet/vercel-action@v20 #deploy
        with:
          vercel-token: 1bSZ5UeO8EQ4QglwvyMkK199 # Required
          github-token: ${{ secrets.GITHUB_TOKEN }} #Optional 
          vercel-args: '--prod' #Optional
          vercel-org-id: DManj4yLeUapRIs6zvt5Rik5  #Required
          vercel-project-id: prj_vXNjNkj1Qtf4AwyDx4zSKjsXrbo8 #Required 
          working-directory: ./image-repo-api
