name: Vercel
on:
  push:
    branches:
      - develop
  pull_request_target:

jobs:
  angular:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: build
        run: |
          cd example/angular
          npm ci
          npx ng build --prod

      - uses: ./
        id: vercel-action-staging
        if: github.event_name == 'pull_request_target'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-token: 1bSZ5UeO8EQ4QglwvyMkK199 
          vercel-org-id: DManj4yLeUapRIs6zvt5Rik5  
          vercel-project-id: prj_vXNjNkj1Qtf4AwyDx4zSKjsXrbo8
          working-directory: image-repo-front
          alias-domains: |
            staging.angular.vercel-action.amond.dev
            pr-{{PR_NUMBER}}.angular.vercel-action.amond.dev
      - uses: ./
        id: vercel-action-production
        if: github.event_name == 'push'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-token: 1bSZ5UeO8EQ4QglwvyMkK199 
          vercel-org-id: DManj4yLeUapRIs6zvt5Rik5  
          vercel-project-id: prj_vXNjNkj1Qtf4AwyDx4zSKjsXrbo8
          working-directory: image-repo-front
          vercel-args: '--prod '
