name: Vercel Deploy
env:
  VERCEL_ORG_ID: DManj4yLeUapRIs6zvt5Rik5  
  VERCEL_PROJECT_ID: prj_vXNjNkj1Qtf4AwyDx4zSKjsXrbo8
on:
  pull_request:
      branches:
      - develop
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=1bSZ5UeO8EQ4QglwvyMkK199
      - name: Build Project Artifacts
        run: vercel build --token=1bSZ5UeO8EQ4QglwvyMkK199
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=1bSZ5UeO8EQ4QglwvyMkK199
